<a href="https://colab.research.google.com/github/SaikrishnaParamkusham/NLP_GEN_AI/blob/main/Encoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

In [5]:
data=pd.DataFrame({"text":["people watch cricket","cricket watch cricket","people give comment","cricket give comment"],"output":[1,1,0,0]})

In [ ]:
data

text  output
0   people watch cricket       1
1  cricket watch cricket       1
2    people give comment       0
3   cricket give comment       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
BOW = CountVectorizer()

In [ ]:
data["text"]

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

In [ ]:
document_matrix = BOW.fit_transform(data["text"])

In [ ]:
document_matrix

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [ ]:
BOW.vocabulary_

{'people': 3, 'watch': 4, 'cricket': 1, 'give': 2, 'comment': 0}

In [ ]:
document_matrix[0].toarray()

array([[0, 1, 0, 1, 1]])

In [ ]:
document_matrix[1].toarray()

array([[0, 2, 0, 0, 1]])

In [ ]:
bigram = CountVectorizer(ngram_range=(2,2))

In [ ]:
trigram = CountVectorizer(ngram_range=(3,3))

In [ ]:
bigram_matrix = bigram.fit_transform(data["text"])

In [ ]:
bigram.vocabulary_

{'people watch': 4,
 'watch cricket': 5,
 'cricket watch': 1,
 'people give': 3,
 'give comment': 2,
 'cricket give': 0}

In [ ]:
trigram_matrix = trigram.fit_transform(data["text"])
trigram.vocabulary_

{'people watch cricket': 3,
 'cricket watch cricket': 1,
 'people give comment': 2,
 'cricket give comment': 0}

In [ ]:
mixgram = CountVectorizer(ngram_range=(1,3))
mixgram.fit_transform(data["text"])
mixgram.vocabulary_

{'people': 8,
 'watch': 13,
 'cricket': 1,
 'people watch': 11,
 'watch cricket': 14,
 'people watch cricket': 12,
 'cricket watch': 4,
 'cricket watch cricket': 5,
 'give': 6,
 'comment': 0,
 'people give': 9,
 'give comment': 7,
 'people give comment': 10,
 'cricket give': 2,
 'cricket give comment': 3}

In [ ]:
data["text"]

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

TF-IDF

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
tfidf = TfidfVectorizer()

In [6]:
tfidf.fit_transform(data["text"]).toarray()

array([[0.        , 0.49681612, 0.        , 0.61366674, 0.61366674],
       [0.        , 0.8508161 , 0.        , 0.        , 0.52546357],
       [0.57735027, 0.        , 0.57735027, 0.57735027, 0.        ],
       [0.61366674, 0.49681612, 0.61366674, 0.        , 0.        ]])

In [9]:
feature_names = tfidf.get_feature_names_out()
print(feature_names)

['comment' 'cricket' 'give' 'people' 'watch']
